services:
  - docker

script:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then 
      docker run
        -v $(pwd):/repo
        -e BRANCH=$TRAVIS_BRANCH
        -e IS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
        -e PROJECT
        -e ENC_PASS_TRAVIS
        -e ENC_PASS_LETS_ENCRYPT
        hollowverse/hollowverse-gae
      ;
    fi

notifications:
  email: false

