service: lets-encrypt

runtime: custom
env: flex

skip_files:
  - node_modules
  - deploy.js

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

health_check:
  enable_health_check: false
